server {
    listen 80;
    server_name _;
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Intentionally exposed for lab02. Students should propose a deny rule.
    location /backup/ {
        autoindex on;
    }
}

