#!/usr/bin/env python3
import argparse
import json
from datetime import datetime


def main() -> int:
    parser = argparse.ArgumentParser(description="Convert an attack report into an exam score.")
    parser.add_argument("report", help="JSON report generated by exam/attack.py")
    parser.add_argument("--minutes", type=float, required=True, help="student completion time in minutes")
    args = parser.parse_args()

    with open(args.report, encoding="utf-8") as f:
        report = json.load(f)

    fixed_points = int(report["fixed_points"])
    time_bonus = 0
    if args.minutes <= 30:
        time_bonus = 10
    elif args.minutes <= 60:
        time_bonus = 6
    elif args.minutes <= 90:
        time_bonus = 3

    score = min(100, fixed_points + time_bonus)
    result = {
        "graded_at": datetime.utcnow().isoformat() + "Z",
        "fixed_points": fixed_points,
        "time_minutes": args.minutes,
        "time_bonus": time_bonus,
        "score": score,
        "all_attacks_failed": bool(report["all_attacks_failed"]),
    }
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
